ARTIFACTS_DIR: "../artifacts"
MODEL:
  img_size: [512, 512, 3]
  scale_factor: 4
  disable_bn: true
  moco_queue:
    max_batches: 8
  temperature: 1
  momentum: 0.999
DATA:
  batch_size: 8
  n_classes: 20
  root_dir: "../data"
  augm:
    crop_size: [256, 256]
OPTIM:
  loss: ""
  optimizer: "AdamW"
  lr: 0.001
  accumulate_gradient: False
  accumulate_gradient_iters: 8
  num_epochs: 100
  num_iterations_val: 50
  save_ckpt_every: 10
  eval_every: 5
  gradient_clip: true
  scheduler: ""
  T_max: 100
  eta_min: 0.000001
